### ISSUE TITLE
cocoapod repo has out of date podspec?

### ISSUE THREAD

**Issue by mikewoodworth** [michaeltyson/TPCircularBuffer#12]
I'm running into problems loading this pod in osx:

[!] The platform of the target `OneLight` (OS X 10.8) is not compatible with `TPCircularBuffer (1.3)`, which does not support `osx`.

The podspec in this github repo seems correct (supports osx 10.8+), the podspec on cocoapods seems to be ios only.

**Comment by michaeltyson** [comment]
Ah, maybe it's time to update the pod then =) Try now, I've just submitted v1.4

**Comment by mikewoodworth** [comment]
that worked, thanks!
