### ISSUE TITLE
Issues with signedness when compiling with aggressive settings on XCode 9

### ISSUE THREAD

**Issue by mman** [michaeltyson/TPCircularBuffer#15]
Hi Micheal,

I have turned on some aggressive compiler checking on my projects, along with the new XCode 9 undefined behavior, runtime behavior, and address sanitizer and uncovered couple of compiler warnings around converting ``int`` to ``uint`` and others in ``TPCircularBuffer`` code.

I wonder whether I should spend some time trying to fix them (read: whether you are interested in pulling these into master).

Attached is an example screenshot from xcode pointing towards buffer ``length``, ``head``, and ``tail`` being ``int32_t`` which can be negative and (from my limited understanding of your code) they would better be ``unsigned`` somethings... 

feel free to close as inappropriate or +1 if you want me to investigate this further...

thanks,
Martin

![screen shot 2017-08-09 at 19 27 06](https://user-images.githubusercontent.com/249814/29135029-0c91d10a-7d39-11e7-9433-4ffc03e7faa5.png)

**Comment by michaeltyson** [comment]
Hey Martin - sure thing, I'll accept pulls!
