### ISSUE TITLE
Compiler Error: TPCircularBuffer.h:159:9: No matching function for call to 'atomic_fetch_add'

### ISSUE THREAD

**Issue by BigSauce** [michaeltyson/TPCircularBuffer#20]
I just integrated TPCircularBuffer into my Swift project via `pod 'TPCircularBuffer', '~> 1.5'`, and I'm getting the following compiler error at line 159 of TPCircularBuffer.h.

![image](https://user-images.githubusercontent.com/1718470/34507481-61c31dda-f004-11e7-9b0c-bda715580043.png)

I see the following [StackOverflow answer](https://stackoverflow.com/a/47946093/931972), which is helpful, but I'm wondering if support for Swift projects could be implemented as part of this library.

Thanks!

**Comment by michaeltyson** [comment]
Just leaving this open for now - I don't have the time presently to look into it, but I can see it'd definitely be useful

**Comment by michaeltyson** [comment]
Should be solved now (dup of #25)
