### ISSUE TITLE
TPCircularBuffer `fillCount` Swift access

### ISSUE THREAD

**Issue by RichAppz** [michaeltyson/TPCircularBuffer#21]
This might be a stupid question but I am currently creating an app that requires the use of `TPCircularBuffer` but I can't see to get access to the `fillCount` - could you guide me in the right direction.

Thanks in advance

**Comment by pablogeek** [comment]
I have the same issue, since the latest update. any thoughts? @RichAppz

**Comment by pablogeek** [comment]
@michaeltyson would be nice if you can provide some help :)

**Comment by michaeltyson** [comment]
Use TPCircularBufferTail to get a pointer to the buffer to read from, and it'll tell you how many bytes you can read (or TPCircularBufferHead for writing, and it'll tell you how much space there is)
