### ISSUE TITLE
using in c++ code and 'atomic_fetch_add'

### ISSUE THREAD

**Issue by oleg-naumenko** [michaeltyson/TPCircularBuffer#25]
had compile error: "No matching function for call to 'atomic_fetch_add'" when using inside obj-c++ and c++ classes. 

changed 
        typedef std::atomic_int atomicInt;
to
        typedef std::atomic<uint32_t> atomicInt;

and it worked. Is this change valid?

**Comment by dave234** [comment]
@oleg-naumenko  Which compiler are you using?

**Comment by oleg-naumenko** [comment]
Apple LLVM 9.0 (Xcode 9.2), GNU++11

**Comment by RishatShamsutdinov** [comment]
[This PR](https://github.com/michaeltyson/TPCircularBuffer/pull/24) solves this issue.

**Comment by BubiDevs** [comment]
Same problem here, @RishatShamsutdinov's fix solved the problem! 

@michaeltyson Do you plan to accept the PR and make a new version for CocoaPods soon?

Thanks a lot!

**Comment by michaeltyson** [comment]
Done!
