### ISSUE TITLE
Redefinition of module TPCircularBuffer

### ISSUE THREAD

**Issue by galileoguzman** [michaeltyson/TPCircularBuffer#27]
Issue:

I have a problem with a submodule using TPCIrucloarBuffer, when I try to build the project every time I got the same error: `Redefinition of module TPCircularBuffer`

Project structure:

- Cocoapods
- Main project
   - Sub module with TPCircularBuffer

Tooling:

- Xcode 9.4
- Cocoapods
- Swift
- MacOS

**Comment by michaeltyson** [comment]
What other pods are you using in your project? Maybe one of those has TPCB in it too?

**Comment by galileoguzman** [comment]
this is my pod file

```
platform:ios, "9.3"
swift_version = "4.0"
use_frameworks!

target 'VmCare' do
	pod 'Alamofire'
	pod 'CocoaLumberjack/Swift'
	pod 'Crashlytics'
	pod 'Fabric'
	pod 'PromiseKit/CorePromise'
	pod 'ScanAPI', :path => 'scanapisdk-10-3-36'
end
```
