### ISSUE TITLE
Add data to the tail of the buffer.

### ISSUE THREAD

**Issue by pablogeek** [michaeltyson/TPCircularBuffer#28]
Hello would be possible to have a function that add bytes to the tail of the buffer instead of in the head? there are some situations where I might want to add data to the tail.

Thanks

**Comment by michaeltyson** [comment]
Hi - not without breaking the thread safety of the utility. You're probably better off using something different.

**Comment by pablogeek** [comment]
@michaeltyson Hi, thanks for the answer. Can you show me an example how this would be done. I will take care of the thread safety.

Thanks!!

**Comment by michaeltyson** [comment]
I'm afraid I don't have the time for that; apologies.

**Comment by pablogeek** [comment]
@michaeltyson Thanks anyway!! sorry to bother You!
