### ISSUE TITLE
New Tag for Swift Package Manager Support

### ISSUE THREAD

**Issue by danhalliday** [michaeltyson/TPCircularBuffer#37]
Hello, and thanks again for this code. I must have been using this for 10 years by now!

I think the repository could do with a new tag to get the SPM support working. Currently when you add 1.6.1 to a package manifest, the following warning is seen:

```swift
.package(url: "https://github.com/michaeltyson/TPCircularBuffer", from: "1.6.1") // => the package manifest at '/Package.swift' cannot be accessed (/Package.swift doesn't exist in file system)
```

When using `branch: "master"` it works. All that’s needed is a new `1.6.2` tag.

**Comment by michaeltyson** [comment]
My pleasure! Ah, good point - thanks, done
