### ISSUE TITLE
How to change buffer size?

### ISSUE THREAD

**Issue by edl00k** [michaeltyson/TPCircularBuffer#4]
Any way to change buffer size (existing buffer)

thanks

**Comment by edl00k** [comment]
found one way but I'm not sure that optimal way

```objective-c
bufferSize = 'new buffer size';

int32_t availableToReadBytes;
uint8_t *tempBuffer = TPCircularBufferTail(&buffer, &availableToReadBytes);
printf("+ availableToReadBytes %d \n", availableToReadBytes);

SInt16 *newBuffer = (SInt16*)malloc(sizeof(SInt16)*availableToReadBytes);
memcpy(newBuffer, tempBuffer, availableToReadBytes);
    
TPCircularBufferCleanup(&buffer);

TPCircularBufferInit(&buffer, bufferSize);

TPCircularBufferProduceBytes(&buffer, newBuffer, availableToReadBytes);
printf("change buffer %d on size: %d \n", buffer_size_default, bufferSize);

// check how many bytes is available
int32_t bytesToRead;
TPCircularBufferTail(&buffer, &bytesToRead);
printf("+ bytesToRead %d \n", availableToReadBytes);
```

**Comment by michaeltyson** [comment]
One warning - if you're doing this on the fly, manipulating the buffer like that kinda breaks it's thread-safeness. Unless this isn't on the fly and you're not using it at the time you're resizing - then that's okay.

**Comment by edl00k** [comment]
thanks for quick reply,
I use that's one time at the time when I'm getting metadata from flac file so that's setup optimal buffer size by metadata for future playback

* stream reader gets a data
* decoder recognizes metadata `and after first block 'STREAMINFO' we can change buffer size for stream reader`
* decoder starts to read data to playback

My issue that after decoding 'STREAMINFO'. Decoder continues to get blocks yet that mean decoder will continue to read data from stream reader. And here I see two ways to resolve:
1. locking getting data from stream in the time a setup new buffer size
2. changing buffer size after getting last block (before playback)

**Comment by edl00k** [comment]
I printed in console the current thread at the reading and changing buffer size, I see that it's same thread. My guess that issue have resolved.

**Comment by edl00k** [comment]
quick note for who are trying to do something similar

please **review your app architecture** again. probably you won't to think in future that buffer size changing is a good idea. I hope that's help you keep time.
