### ISSUE TITLE
Podspec update for osx

### ISSUE THREAD

**Issue by iamyellow** [michaeltyson/TPCircularBuffer#8]
hey! thanks for this great lib :+1: 

btw, I've found a problem with very easy solution. I tried to use your lib w/ cocoapods but w/ osx target, but it failed telling that incompatible target message. i've just updated my mac and installed cocoapods, so i guess is the latest version. it turns out that the podspec file needs to specify both platforms in this way:

s.ios.platform = :ios, "4.3"
s.osx.platform = :osx, "10.10"

instead of:

s.platform           = :ios, '4.3', :osx, '10.0'

i made a simple local podspec and it works!

**Comment by michaeltyson** [comment]
Thanks! Okay, this one's sorted by SHA e7efdcb03b4a4f1cfad7bd39fe69ec2629003865
